### ISSUE TITLE
Datacore Settings Tab - put code in its own file

### ISSUE THREAD

**Issue by TfTHacker** [blacksmithgu/datacore#13]
https://github.com/blacksmithgu/datacore/blob/9bc601f4cdac12181be8c4bad2063eb5f676f612/src/main.ts#L75

I notice the UI for the Settings tab is in the main.ts. I know this has been a convention in the past, but I recommend putting this code into its own file in the UI folder.

Reasons:
- Let the main.ts be just that initialization code that gets the plugin loaded.
- Keeping the UI together can make it easier to find by new devs looking at the code.

If you disagree, mark this completed, not a big issue by any means.

**Comment by xDovos** [comment]
It makes sense but don't forget that this is all still pre alpha and the ui stuff is just there so that there is something that makes testing work.
There is still 80+% of the features and functions missing and it makes little sense to already optimise the code in ways that only bring readability and nothing else.

**Comment by blacksmithgu** [comment]
I would put it in a separate file but to my remembrance every time I've tried I get strange TypeScript circular reference issues. Perhaps sprinkling `import type` in enough places would fix it.

**Comment by TfTHacker** [comment]
Looks like this issue is completed with src/settings.ts.

Tnx! It is so nice to see this project inches forward.
