### ISSUE TITLE
Do you plan to implement the function of free sorting in the Datacore view.

### ISSUE THREAD

**Issue by chiusuan** [blacksmithgu/datacore#41]
For example, in a table, the order can be adjusted by dragging table rows and columns. In the card, you can move it up, down, left, and right.

**Comment by blacksmithgu** [comment]
Column sorting (i.e., re-ordering columns) will be supported; implementing it via drag and drop is actually surprisingly hard so that may not be available immediately, but some way to move columns around will be.

Row-level sorting will not be drag-and-droppable probably, at least not now. Datacore supports sorting, but it is always on data in the actual rows. That being said, this can probably be kind of simulated by adding a "priority" or "order" field to the table which you can change to specify custom orderings.

**Comment by GamerGirlandCo** [comment]
i can vouch for drag and drop being difficult to implement without a heavyweight library or reinventing the wheel 😭
